services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
    tty: true
    stdin_open: true
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.238
    ports:
      - "8081:8081"   
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19005:19005"
      - "19006:19006"
  
  back:
    build:
      context: ./back/      #dockerfileのディレクトリ
      dockerfile: Dockerfile
    container_name: go_app
    volumes:
      - ./back:/usr/src/app # ホストのコードをコンテナにマウント（任意、開発用）
    ports:
      - "8080:8080"    # Goアプリが:8080でListenしている場合
    #command: [""]   # CMD 上書き可能（Dockerfileにもあるが明示）
    tty: true
