# Use postgres/example user/password credentials

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    ports:
     - 8989:5432

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8888:8080

volumes:
  pgdata:
