version: "3.8"
services:
  node:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./app/:/usr/src/app
    tty: true
    stdin_open: true
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.238
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19005:19005"
      - "19006:19006"
